#1362 [Core] fix: require category class in mod
Evarisk/DoliSMQ pull request #1369
Opened 2023-07-07 07:38 UTC by evarisk-theo

2023-07-07 16:06 UTC, nicolas-eoxia requested changes

2023-07-07 16:06 UTC, nicolas-eoxia commented on core/modules/modDoliSMQ.class.php
> +			include_once DOL_DOCUMENT_ROOT . '/categories/class/categorie.class.php';
Require_once est mieux

2023-07-07 16:06 UTC, nicolas-eoxia commented on class/answer.class.php
> +		$refAnswerModName = empty($conf->global->DOLISMQ_ANSWER_ADDON) ? 'mod_answer_standard' : $conf->global->DOLISMQ_ANSWER_ADDON;
Rajouter également le check sur le require de la class modAnswer ca améliorera si jamais on change le modèles de réf

2023-07-12 08:08 UTC, evarisk-theo commented on class/answer.class.php
> +		$refAnswerModName = empty($conf->global->DOLISMQ_ANSWER_ADDON) ? 'mod_answer_standard' : $conf->global->DOLISMQ_ANSWER_ADDON;
voir dolisirh fichier projet

2023-07-18 09:32 UTC, merged